### PR TITLE
adding usart function to modify baud on the fly

### PR DESCRIPTION
**Pull request by nextez**

### CODE REVIEW

**Comment by othane** [comment]
OK two things:

1) rather than modify the ST libs ... just put all the code into `hal/stm32f4/uart.c` please
2) also can we do the same for the stm32f373, ie?
```
  /*---------------------------- USART BRR Configuration -----------------------*/
  /* Configure the USART Baud Rate -------------------------------------------*/
  RCC_GetClocksFreq(&RCC_ClocksStatus);
  
  if (USARTx == USART1)
  {
    apbclock = RCC_ClocksStatus.USART1CLK_Frequency;
  }
  else if (USARTx == USART2)
  {
    apbclock = RCC_ClocksStatus.USART2CLK_Frequency;
  }
  else 
  {
    apbclock = RCC_ClocksStatus.USART3CLK_Frequency;
  }  
  
  /* Determine the integer part */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    /* (divider * 10) computing in case Oversampling mode is 8 Samples */
    divider = (uint32_t)((2 * apbclock) / (USART_InitStruct->USART_BaudRate));
    tmpreg  = (uint32_t)((2 * apbclock) % (USART_InitStruct->USART_BaudRate));
  }
  else /* if ((USARTx->CR1 & CR1_OVER8_Set) == 0) */
  {
    /* (divider * 10) computing in case Oversampling mode is 16 Samples */
    divider = (uint32_t)((apbclock) / (USART_InitStruct->USART_BaudRate));
    tmpreg  = (uint32_t)((apbclock) % (USART_InitStruct->USART_BaudRate));
  }
  
  /* round the divider : if fractional part i greater than 0.5 increment divider */
  if (tmpreg >=  (USART_InitStruct->USART_BaudRate) / 2)
  {
    divider++;
  } 
  
  /* Implement the divider in case Oversampling mode is 8 Samples */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    /* get the LSB of divider and shift it to the right by 1 bit */
    tmpreg = (divider & (uint16_t)0x000F) >> 1;
    
    /* update the divider value */
    divider = (divider & (uint16_t)0xFFF0) | tmpreg;
  }
  
  /* Write to USART BRR */
  USARTx->BRR = (uint16_t)divider;

```

**Comment by nextez** [comment]
commit updated, no changes to ST libs :)

**Comment by othane** [comment]
I just tried to build this for the stm32f373 and it failed ... I have made the required changes in this commit https://github.com/othane/mos/commit/55de483f11f942552c1a9e44c86d4cda1f29fd91 ... please cherry-pick them across to your branch and maybe squish these 3 commits into 1 and I think that will do

NB: I have not tested this code on real HW, but as it is an additional API I don't mind adding (since it wont break anything if it is buggy), but it does need to not break the build is the only thing

**Comment by nextez** [comment]
PR updated, commits squashed :)

**Pull request merged**
